export const FETCH_ETH_PRICE = 'FETCH_ETH_PRICE';

export const FETCH_TOKENS_COUNT = 'FETCH_TOKENS_COUNT';
export const FETCH_TOKENS_COUNT_BY_STATUS = 'FETCH_TOKENS_COUNT_BY_STATUS';
export const FETCH_TOKENS_DEPOSITS = 'FETCH_TOKENS_DEPOSITS';

export const FETCH_BADGES_COUNT = 'FETCH_BADGES_COUNT';
export const FETCH_BADGES_COUNT_BY_STATUS = 'FETCH_BADGES_COUNT_BY_STATUS';
export const FETCH_BADGES_CROWDFUNDING = 'FETCH_BADGES_CROWDFUNDING'
export const FETCH_BADGES_DEPOSITS = 'FETCH_BADGES_DEPOSITS';

export const FETCH_CROWDFUNDING_TOKENS = 'FETCH_TOKENS_CROWDFUNDING';
export const CROWDFUNDING_PAGE_NEXT = 'CROWDFUNDING_PAGE_NEXT'
export const CROWDFUNDING_PAGE_PREVIOUS = 'CROWDFUNDING_PAGE_PREVIOUS';
